from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
import datetime

def create_calendar_events(access_token, claude_schedule_json):
    """
    Takes the access token from React and the parsed JSON from Claude,
    and creates events in the user's primary Google Calendar.
    """
    try:
        # Authorize google calendar api with token from React
        credentials = Credentials(token=access_token)
        service = build('calendar', 'v3', credentials=credentials)

        created_events = []

        # Loop through JSON array generated by Claude
        for task in claude_schedule_json:
            
            # Format the event data for Google Calendar
            # instruct Claude to output dates in ISO format (YYYY-MM-DDTHH:MM:SS)
            event_body = {
                'summary': task.get('title', 'Study Block'),
                'description': f"Wellness Tip: {task.get('healthTip', 'Take a breather!')}",
                'start': {
                    'dateTime': task.get('startTime'), # e.g., '2026-07-17T15:00:00-07:00'
                    'timeZone': 'America/Los_Angeles', # pass the user's timezone!
                },
                'end': {
                    'dateTime': task.get('endTime'),
                    'timeZone': 'America/Los_Angeles',
                },
                'colorId': '5', # Optional: Gives the events a specific color (5 is yellow)
            }

            # Insert into the primary calendar
            event_result = service.events().insert(
                calendarId='primary', 
                body=event_body
            ).execute()

            created_events.append(event_result.get('htmlLink'))

        return {"success": True, "links": created_events}
    
    except Exception as e:
        print(f"Error creating calendar events: {e}")
        return{"success": False, "error": str(e)}
